var namespacePyHoot_1_1services =
[
    [ "answer", "d3/daa/classPyHoot_1_1services_1_1answer.html", "d3/daa/classPyHoot_1_1services_1_1answer" ],
    [ "check_move_next_page", "d1/d37/classPyHoot_1_1services_1_1check__move__next__page.html", "d1/d37/classPyHoot_1_1services_1_1check__move__next__page" ],
    [ "check_move_question", "d2/d96/classPyHoot_1_1services_1_1check__move__question.html", "d2/d96/classPyHoot_1_1services_1_1check__move__question" ],
    [ "check_name", "d4/df1/classPyHoot_1_1services_1_1check__name.html", "d4/df1/classPyHoot_1_1services_1_1check__name" ],
    [ "check_test", "db/d18/classPyHoot_1_1services_1_1check__test.html", "db/d18/classPyHoot_1_1services_1_1check__test" ],
    [ "check_test_exist", "d9/dd4/classPyHoot_1_1services_1_1check__test__exist.html", "d9/dd4/classPyHoot_1_1services_1_1check__test__exist" ],
    [ "check_timer_change", "d8/d4f/classPyHoot_1_1services_1_1check__timer__change.html", "d8/d4f/classPyHoot_1_1services_1_1check__timer__change" ],
    [ "diconnect_user", "dd/dff/classPyHoot_1_1services_1_1diconnect__user.html", "dd/dff/classPyHoot_1_1services_1_1diconnect__user" ],
    [ "get_answers", "d0/d3b/classPyHoot_1_1services_1_1get__answers.html", "d0/d3b/classPyHoot_1_1services_1_1get__answers" ],
    [ "get_information", "dc/d11/classPyHoot_1_1services_1_1get__information.html", "dc/d11/classPyHoot_1_1services_1_1get__information" ],
    [ "get_join_number", "d4/d49/classPyHoot_1_1services_1_1get__join__number.html", "d4/d49/classPyHoot_1_1services_1_1get__join__number" ],
    [ "get_question", "dc/dde/classPyHoot_1_1services_1_1get__question.html", "dc/dde/classPyHoot_1_1services_1_1get__question" ],
    [ "get_score", "d2/de3/classPyHoot_1_1services_1_1get__score.html", "d2/de3/classPyHoot_1_1services_1_1get__score" ],
    [ "get_title", "db/df0/classPyHoot_1_1services_1_1get__title.html", "db/df0/classPyHoot_1_1services_1_1get__title" ],
    [ "get_xml_leaderboard", "d3/ded/classPyHoot_1_1services_1_1get__xml__leaderboard.html", "d3/ded/classPyHoot_1_1services_1_1get__xml__leaderboard" ],
    [ "getnames", "d5/d9d/classPyHoot_1_1services_1_1getnames.html", "d5/d9d/classPyHoot_1_1services_1_1getnames" ],
    [ "homepage", "d5/db3/classPyHoot_1_1services_1_1homepage.html", "d5/db3/classPyHoot_1_1services_1_1homepage" ],
    [ "join", "df/d3a/classPyHoot_1_1services_1_1join.html", "df/d3a/classPyHoot_1_1services_1_1join" ],
    [ "move_to_next_question", "d3/dd4/classPyHoot_1_1services_1_1move__to__next__question.html", "d3/dd4/classPyHoot_1_1services_1_1move__to__next__question" ],
    [ "moved_to_next_page", "d0/d5e/classPyHoot_1_1services_1_1moved__to__next__page.html", "d0/d5e/classPyHoot_1_1services_1_1moved__to__next__page" ],
    [ "new", "d3/d6f/classPyHoot_1_1services_1_1new.html", "d3/d6f/classPyHoot_1_1services_1_1new" ],
    [ "order_move_all_not_answered", "d4/d40/classPyHoot_1_1services_1_1order__move__all__not__answered.html", "d4/d40/classPyHoot_1_1services_1_1order__move__all__not__answered" ],
    [ "order_move_all_players", "d7/d19/classPyHoot_1_1services_1_1order__move__all__players.html", "d7/d19/classPyHoot_1_1services_1_1order__move__all__players" ],
    [ "register_quiz", "d7/d6f/classPyHoot_1_1services_1_1register__quiz.html", "d7/d6f/classPyHoot_1_1services_1_1register__quiz" ],
    [ "Service", "db/d1a/classPyHoot_1_1services_1_1Service.html", "db/d1a/classPyHoot_1_1services_1_1Service" ],
    [ "set_timer_change", "da/d4f/classPyHoot_1_1services_1_1set__timer__change.html", "da/d4f/classPyHoot_1_1services_1_1set__timer__change" ],
    [ "start_question", "d8/d22/classPyHoot_1_1services_1_1start__question.html", "d8/d22/classPyHoot_1_1services_1_1start__question" ],
    [ "XMLService", "d8/d0d/classPyHoot_1_1services_1_1XMLService.html", "d8/d0d/classPyHoot_1_1services_1_1XMLService" ]
];